services:
  backend:
    build: backend
    ports:
      - "9988:8080"
    restart: unless-stopped
    environment:
      - VK_APP_ID
      - DB_NAME
      - DB_HOST
      - DB_PASSWORD
      - DB_PORT
      - DB_USER
      - VK_APP_SERVICE_TOKEN
      - VK_GROUP_ID
      - VK_ACCESS_TOKEN
      - COOKIES_DOMAIN
      - OPENAI_SECRET_KEY
      - GENERAL_SECRET_KEY_BASE64
      - FRONTEND_HOST
      - FRONTEND_BASE_PATH
      - STABILITY_AI_API_KEY
  frontend:
    build: frontend
    ports:
      - "9080:80"
    restart: unless-stopped
    environment:
      - API_URL
      - VK_APP_ID
      - FRONTEND_BASE_PATH
