version: "3"
services:
  backend:
    build: backend
    ports:
      - "9988:8080"
    environment:
      - VK_APP_ID
      - DB_NAME
      - DB_HOST
      - DB_PASSWORD
      - DB_PORT
      - DB_USER
      - VK_APP_SERVICE_TOKEN
      - VK_GROUP_ID
      - COOKIES_DOMAIN
      - OPENAI_SECRET_KEY
      - GENERAL_SECRET_KEY_BASE64
      - FRONTEND_URL_BASE
  frontend:
    build: frontend
    ports:
      - "9080:3000"
    environment:
      - API_URL
      - VK_APP_ID
      - FRONTEND_BASE_PATH
  bot:
    build: bot
    ports:
      - "9005:9005"
    environment:
      - BACKEND_URL=backend:8080
      - DB_NAME
      - DB_HOST
      - DB_PASSWORD
      - DB_PORT
      - DB_USER
      - OPENAI_SECRET_KEY
      - VK_ACCESS_TOKEN
      - VK_GROUP_ID
      - METAPHOR_API_KEY
      - FILE_HOSTING_PORT=9005
      - FILE_HOSTING_URL_BASE
      - FILE_HOSTING_MAX_STORAGE_SIZE_BYTES=67108864 # 64 MB
    depends_on:
      - backend